Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Ecomm.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Ecomm.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/LatestNew.cs
namespace Ecomm.Models
{
    public class LatestNew
    {
        public int Id { get; set; }
        public string NewsImage { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Date { get; set; }
    }
}

Models/Product.cs
namespace Ecomm.Models
{
    public class Product
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ProductImage { get; set; }
        public decimal UnitPrice { get; set; }
        public bool Featured { get; set; }
        public int NumberOfSale { get; set; }
        public int Ratings { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public decimal DiscountedUnitPrice { get; set; }
        public int PercentOff { get; set; }
        public int Quantity { get; set; }
        public bool Availability { get; set; }
    }
}

Models/User.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Ecomm.Models
{
    public class User
    {
        public int Id { get; set; }
        
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [DisplayName("Fullname")]
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

Controllers/HomeController.cs
using Ecomm.Contracts;
using Ecomm.Models;
using Ecomm.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;

namespace Ecomm.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductService _productService;
        private readonly ILatestNews _latestNewsService;
        public HomeController(ILogger<HomeController> logger, IProductService productService, ILatestNews latestNewsService)
        {
            _logger = logger;
            _productService = productService;
            _latestNewsService = latestNewsService;
        }
        public async Task<IActionResult> Index(UserProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                productViewModel.Products = await _productService.GetAllProducts();
                productViewModel.LatestNews = await _latestNewsService.GetAllLatestNews();
                return View(productViewModel);
            }
            return View(productViewModel);
        }     
        public IActionResult Privacy()
        {
            return View();
        }
        public async Task<IActionResult> LoadMore(int page=1)
        {
            UserProductViewModel productViewModel = new UserProductViewModel();
            productViewModel.Products = await _productService.GetAllProducts();
            productViewModel.IsSuccess = true;
            productViewModel.ProductPerPage = 5;
            productViewModel.CurrentPage = page;
            return View(productViewModel);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using Ecomm.Contracts;
using Ecomm.Models;
using Ecomm.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ecomm.Controllers
{
    public class LoginController : Controller
    {
        private readonly IAuthentication _authService;
        public LoginController(IAuthentication authService)
        {
            _authService = authService;
        }
        public IActionResult Index()
        {

            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index(User user)
        {
            user = await _authService.Login(user.Email, user.Password);
            if (user == null) ViewBag.InvalidLoginDetails = "Invalid Credentials";
            else
            {
                UserProductViewModel productViewModel = new UserProductViewModel();
                productViewModel.IsSuccess = true;
                return RedirectToAction("Index", "Home", productViewModel);
            }
            return View();
        }
    }
}

Controllers/ProductController.cs
using Ecomm.Contracts;
using Ecomm.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Ecomm.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ILatestNews _latestNewsService;
        private static int _productId;
        public ProductController(IProductService productService, ILatestNews latestNewsService)
        {
            _productService = productService;
            _latestNewsService = latestNewsService;
        }
        public async Task<IActionResult> Index(int id)
        {
            if(id > 0)
            {
                _productId = id;
            }
            UserProductViewModel userProductViewModel = new UserProductViewModel();
            userProductViewModel.Product = await _productService.GetProductById(_productId);
            userProductViewModel.Products = await _productService.GetAllProducts();
            return View(userProductViewModel);
        }
        
    }
}

Controllers/RegistrationController.cs
using Ecomm.Contracts;
using Ecomm.Models;
using Ecomm.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Ecomm.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly IUserService _userService;
        public RegistrationController(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index(User user)
        {
            if (user == null) ViewBag.InvalidLoginDetails = "Please fill the form";
            else
            {
               bool isuser = await _userService.AddUser(user);
                if(isuser == true)
                {
                    UserProductViewModel productViewModel = new UserProductViewModel();
                    productViewModel.IsSuccess = true;
                    return RedirectToAction("Index", "Home", productViewModel);
                }
            }
            return View();
        }
    }
}

Views/Home/Index.cshtml
 @model Ecomm.ViewModel.UserProductViewModel
@{
    ViewData["Title"] = "Home Page";
}
 <section class="top-container">
                <header class="showcase">
                    <p>
                        Super Flash Sale<br> 50% Off
                    </p>
                </header>
</section>
<!--Boxes Section-->
<section class="Boxes-section">
    <div class="boxes">
        <div class="box box1">
            <div class="box-overlay">
                <div class="text-adjust" class="box-text">FS - QUILTED MAXI<br> CROSS BAG</div>
                <p class="box-price">
                    <span class="featured_productPrice price-strike-through">$534,33</span>&nbsp
                    <span class="initPrice new-price">24% off</span>
                    <span  class="discount-price-one">299,43</span>
                </p>
            </div>
        </div>
        <div class="box box2">
            <div class="box-overlay">
                <div class="text-adjust" class="box-text">FS - NIKE AIR<br> MAX 270 REACT...</div>
                <span  class="discount-price-two">299,43</span>
                <p class="box-price-center">
                    <span>
                        <span class="featured_productPrice price-strike-through">$534,33</span>&nbsp
                        <span class="initPrice new-price">24% off</span>
                    </span>
                </p>
            </div>
        </div>
        <div class="box box3">
            <div class="box-overlay">
                <div class="text-adjust" class="box-text">FS - NIKE AIR<br> MAX 270 REACT...</div>
                <p class="box-price-center">
                    <span>
                        <span class="featured_productPrice price-strike-through">$534,33</span>&nbsp
                        <span class="initPrice new-price">24% off</span>
                    </span>
                </p>
            </div>
        </div>
    </div>
</section>
    <!--Info Section-->
<section class="info">
    <div class="best-seller">
        <h1>BEST SELLER</h1>
    </div>
    <div id="best-seller-adjust">
        <ul id="best-seller-ul-adjust">
            <li><a style="color: #46BCF7;">All</a></li>
            <li><a>Bags</a></li>
            <li><a>Sneakers</a></li>
            <li><a>Belt</a></li>
            <li><a>Sunglasses</a></li>
        </ul>
    </div>
    <div class="Boxes-section" style="padding:0px 120px">
        <div class="best-seller-items">
        @{
                int count = 0;
            foreach(var product in Model.Products.OrderBy(x=>x.NumberOfSale).ToList())
                    {   
                            if(count < 8)
                            {  <a asp-controller="Product" asp-action="index" asp-route-id="@product.Id">
                                 <div class="best-seller-box1">
                                <div class="best-seller-box"><img src=@product.ProductImage.ToString() width="100%"></div>
                                <div id="text">
                                    @product.Name 
                                </div>
                                <div id="features-detail">
                            @{
                                for(int i = 0; i < 5; i++)
                                {
                                    if(i < product.Ratings)
                                    {
                                        <i class="fa-solid fa-star stars-ratings"></i>
                                    }
                                    else
                                    {    
                                        <i class="fa fa-star stars-gray"></i>
                                    }
                                }
                            }
                            <p>
                            @{
                                int amount = (int) product.UnitPrice;
                                int discountAmount = (int) product.DiscountedUnitPrice;
                                string price = Ecomm.Utilities.PricePunctuation.PriceComma($"{amount}");
                                string discountedPrice = Ecomm.Utilities.PricePunctuation.PriceComma($"{discountAmount}");
                            }
                                <span class="featured_productPrice price-color">@discountedPrice</span> 
                                <span class="initPrice price-strike-through">@price</span>
                                <span class="initPrice new-price">@product.PercentOff% off</span>
                            </p>
                            </div>
                        </div>

                        
                                </a>
                         count++;      
                }
            }
        } 
        </div>
    </div>
</section >
<section class="info">
    <div class="best-seller">
            @{
                if(Model.IsSuccess == false)
                {
                    <h3 id="load-more">LOAD MORE</h3>   
                }
                else
                {
                    <a asp-action="LoadMore" id="load-more"><h3>LOAD MORE</h3></a>
                }
            }
    </div>
        <section class="load-more">
            <div class="inner-content">
                <div>
                    <h1 class="adidas">
                        ADIDAS MEN RUNNING<br><br> SNIKERS
                    </h1>
                    <h3>
                        performance and design. Taken right to the edge
                    </h3>
                    <span id="shop-now">
                        SHOP NOW
                    </span>
                </div>
                </div>
            <div class="best-seller-img">
                <img src="~/img/Show More Shoe.png" alt="" height="100%" > 
            </div>
        </section>
</section>
<section class="services">
    <div style="width:250px">
        <img src="~/img/shipping.png"  class="services-img-position" src height="100%">
        <h3 class="services-p">FREE SHIPPING</h3>
        <p>
            lorem ipsu is simply a dummy text of th printing and typesetting industrt
        </p>
    </div>
    <div style="width:250px">
        <img  class="services-img-position" src="~/img/Path 1.png" height="100%">
        <img class="services-img-position-second" src="~/img/Path 2.png" height="100%">
        <h3 class="services-p">100% REFUND</h3>
        <p>
            lorem ipsu is simply a dummy text of th printing and typesetting industrt
        </p>
    </div>
    <div style="width:250px">
        <img src="~/img/Path 4.png" class="services-img-position" src height="100%">
        <h3 class="services-p">SUPPORT 24/7</h3>
        <p>
            lorem ipsu is simply a dummy text of th printing and typesetting industrt
        </p>
    </div>
</section>
<section class="info">
    <div class="best-seller">
        <h1>LATEST NEWS</h1>
    </div>
    <section class="latest-news">
    @foreach(var news in Model.LatestNews)
    {
        <div class="latest-inner">
            <div class="overlay latest-img">
                <img src= @news.NewsImage.ToString()  src width="100%">
            </div>
            <div class="overlay">
                <h5 class="latest-date">@news.Date</h5>
                <h3 style="text-align: left;">
                    @news.Title
                </h3>
                <p  style="text-align: left;">
                    @news.Body
                </p>
            </div>
        </div>
    }
    </section>
</section>
<section class="info">
    <div class="best-seller">
        <h1>FEATURED PRODUCTS</h1>
    </div>
    <section class="featured" >
        @foreach(var featuredProduct in Model.Products)
        {
            if (featuredProduct.Featured)
            {
                <a asp-action="Product">
                    <div class="featured-column">
                    <div id="featured-column-inner">
                        <img src=@featuredProduct.ProductImage  id="featured-image" width="100%">
                    </div>
                    <div id="features-detail">
                        <h3>@featuredProduct.Name</h3>
                        @{
                            for(int i = 0; i < 5; i++)
                            {
                                if(i < featuredProduct.Ratings)
                                {
                                    <i class="fa-solid fa-star stars-ratings"></i>
                                }
                                else
                                {
                                    <i class="fa fa-star stars-gray"></i>
                                }
                            }
                        }
                        <p>
                            @{
                                int amount = (int) featuredProduct.UnitPrice;
                                int discountAmount = (int) featuredProduct.DiscountedUnitPrice;
                                string price = Ecomm.Utilities.PricePunctuation.PriceComma($"{amount}");
                                string discountedPrice = Ecomm.Utilities.PricePunctuation.PriceComma($"{discountAmount}");
                            }
                            <span class="featured_productPrice price-color">@discountedPrice</span> 
                            <span class="initPrice price-strike-through">@price</span>
                            <span class="initPrice new-price">@featuredProduct.PercentOff% off</span>
                        </p>
                    </div>
                </div> 
                </a>
            }
        }
    </section>
</section>
<section class="centered-form">
    <form>
        <input class="input"><input class="button" type="submit">
    </form>
</section>

Views/Login/Index.cshtml
@model Ecomm.Models.User
@{
    ViewBag.Title = "Login Page";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<div class="login-container">
        <form method="post" asp-action="index" class="login-form">
            <h2>Login</h2>
            <h5 style="color:red">@ViewBag.InvalidLoginDetails</h5>
            <input asp-for="Email" type="email" placeholder="Enter Email Address">
            <input asp-for="Password" type="password" placeholder="password">
            <input class="login-button" value="Login" type="submit">
            <a asp-controller="Registration" asp-action="index">SignUp</a>
        </form>
</div>

Views/Shared/_Layout.cshtml
 @model Ecomm.ViewModel.UserProductViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]E-Comm</title>
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <script src="https://kit.fontawesome.com/d89fdb6161.js" crossorigin="anonymous"></script>
	    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
    <header>
       <div class="content-wrap">
            <div class="wrapper">
            <!--Nav Begins-->
            <nav class="nav1">
                <div class="Navbar">
                    <div class="Navbar__Link Navbar__Link-brand" >
                        <div id="left-nav">
                            <span id="nav-item-adjust">EN<i class="fa-solid fa-caret-down" id="currency" id="nav-item-adjust"></i></span>
                            <span id="nav-item-adjust">USD<i class="fa-solid fa-caret-down" id="currency" id="nav-item-adjust"></i></span>
                        </div>
                    </div>
                <div class="Navbar__Items Navbar__Items--right" id="nav-move-right">
                    <div class="Navbar__Link">
                    @{
                        if(Model.IsSuccess == false)
                        {
                          <span><a class="link-color" asp-controller="Login" asp-action="Index">Login</a></span>    
                        }
                        else
                        {
                           <span><i class="fa-regular fa-user" id="nav-item-adjust"></i><a class="link-color">My Profile</a></span>
                        }
                       }
                        
                    </div>
                    <div class="Navbar__Link" >
                        <span id="nav-item-adjust"><i class="fa-solid fa-cart-shopping"></i></i></span>
                    </div>
                    <div class="Navbar__Link">
                        <span id="nav-item-adjust">Items</i></span>
                    </div>
                    <div class="Navbar__Link">
                        <span>0.00<i class="fa-solid fa-magnifying-glass" id="nav-item-adjust"></i></i></span>
                    </div>
                    @if(Model.IsSuccess == true)
                     {
                        <span><a class="link-color" asp-controller="Login" asp-action="Index">SignOut</a></span> 
                     }
                </div>
            </nav>
            <nav class="main-nav">
                <div class="brand">
                    <div>
                        <span><img src="~/img/Icon.png" alt="logo" class="logo" height="100%">
                    </div>
                     <div >
                        <h4 id="ecomm">
                             E-Comm
                        </h4>
                     </div>
                </div>
                <ul class="Navbar__Itemss">
                    <li class="Navbar__Link Navbar__Link-toggle" id="nav2-adjust-right">
                        <i class="fa-solid fa-bars"></i>
                    </li>
                    <li class="Navbar__Items"><a id="home">Home</a></li>
                    <li class="Navbar__Items"><a>BAG</a></li>
                    <li class="Navbar__Items"><a>SNEAKERS</a></li>
                    <li class="Navbar__Items"><a>BELT</a></li>
                    <li class="Navbar__Items"><a>CONTACT</a></li>
                </ul>
            </nav>
        </div>
            <!--Nav Ends-->
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--Footer-->
            <footer class="footer">
                <div class="footer-row-one">
                    <div style="width:200px; margin-left:100px;">
                        <div class="brand" style="width:150px">
                            <div>
                                <span><img src="img/Icon.png" alt="logo" class="logo" height="100%">
                            </div>
                             <div >
                                <h4 id="ecomm">
                                     E-Comm
                                </h4>
                             </div>
                        </div>
                        <p>lorem ipsu is simply a dummy text of th printing and typesetting industry</p>
                    </div>
                    <div class="footer-items">
                        <h2>Follow US</h2>
                        <p>lorem ipsu is simply a dummy text of th printing and typesetting industry</p>
                        <i class="fa-brands fa-facebook-f facebook-socials"></i><i class="fa-brands fa-twitter twitter-socials"></i>
                    </div>
                    <div class="footer-items">
                        <h2>Contact US</h2>
                        <p>lorem ipsu is simply a dummy text of th printing and typesetting industry</p>
                    </div>
                </div>
                <div class="footer-row-two">
                    <div class="footer-items">
                        <h2>Information</h2>
                       <span>About Us</span>
                       <span>Information</span>
                       <span>Privacy policy</span>
                       <span>Terms and Conditions</span>
                    </div>
                    <div class="footer-items">
                        <h2>Services</h2>
                        <span>About Us</span>
                       <span>Information</span>
                       <span>Privacy policy</span>
                       <span>Terms and Conditions</span>
                    </div>
                    <div class="footer-items">
                        <h2>My Account</h2>
                        <span>About Us</span>
                       <span>Information</span>
                       <span>Privacy policy</span>
                       <span>Terms and Conditions</span>
                    </div>
                    <div class="footer-items">
                        <h2>Our Offers</h2>
                        <span>About Us</span>
                        <span>Information</span>
                        <span>Privacy policy</span>
                        <span>Terms and Conditions</span>
                    </div>
                </div>
           </footer>
         </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
<!DOCTYPE html>

<html>
<head>
     <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]E-Comm</title>
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <script src="https://kit.fontawesome.com/d89fdb6161.js" crossorigin="anonymous"></script>
	    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/login.css"/>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]E-Comm</title>
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <script src="https://kit.fontawesome.com/d89fdb6161.js" crossorigin="anonymous"></script>
	    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
        <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
    />
    <link rel="stylesheet" href="~/css/LoadMore.css"/>
</head>
<body>
    <header>
       <div class="content-wrap">
            <div class="wrapper">
            <!--Nav Begins-->
            <nav class="nav1">
                <div class="Navbar">
                    <div class="Navbar__Link Navbar__Link-brand" >
                        <div id="left-nav">
                            <span id="nav-item-adjust">EN<i class="fa-solid fa-caret-down" id="currency" id="nav-item-adjust"></i></span>
                            <span id="nav-item-adjust">USD<i class="fa-solid fa-caret-down" id="currency" id="nav-item-adjust"></i></span>
                        </div>
                    </div>
                <div class="Navbar__Items Navbar__Items--right" id="nav-move-right">
                    <div class="Navbar__Link">
                    @{
                        if(Model.IsSuccess == false)
                        {
                          <span><a class="link-color" asp-controller="Login" asp-action="Index">Login</a></span>    
                        }
                        else if (Model.IsSuccess == true)
                        {
                           <span><i class="fa-regular fa-user" id="nav-item-adjust"></i><a class="link-color" asp-controller="Login" asp-action="Index">My Profile</a></span>
                        }
                       }  
                    </div>
                    <div class="Navbar__Link" >
                        <span id="nav-item-adjust"><i class="fa-solid fa-cart-shopping"></i></i></span>
                    </div>
                    <div class="Navbar__Link">
                        <span id="nav-item-adjust">Items</i></span>
                    </div>
                    <div class="Navbar__Link">
                        <span>0.00<i class="fa-solid fa-magnifying-glass" id="nav-item-adjust"></i></i></span>
                    </div>
                </div>
            </nav>
            <nav class="main-nav">
                <div class="brand">
                    <div>
                        <span><img src="~/img/Icon.png" alt="logo" class="logo" height="100%">
                    </div>
                     <div >
                        <h4 id="ecomm">
                             E-Comm
                        </h4>
                     </div>
                </div>
                <ul class="Navbar__Itemss">
                    <li class="Navbar__Link Navbar__Link-toggle" id="nav2-adjust-right">
                        <i class="fa-solid fa-bars"></i>
                    </li>
                    <li class="Navbar__Items"><a id="home">Home</a></li>
                    <li class="Navbar__Items"><a>BAG</a></li>
                    <li class="Navbar__Items"><a>SNEAKERS</a></li>
                    <li class="Navbar__Items"><a>BELT</a></li>
                    <li class="Navbar__Items"><a>CONTACT</a></li>
                </ul>
            </nav>
        </div>
            <!--Nav Ends-->
    </header>
    <div>
        @RenderBody()
    </div>
    <!--Footer-->
            <footer class="footer">
                <div class="footer-row-one">
                    <div style="width:200px; margin-left:100px;">
                        <div class="brand" style="width:150px">
                            <div>
                                <span><img src="~/img/Icon.png" alt="logo" class="logo" height="100%">
                            </div>
                             <div >
                                <h4 id="ecomm">
                                     E-Comm
                                </h4>
                             </div>
                        </div>
                        <p>lorem ipsu is simply a dummy text of th printing and typesetting industry</p>
                    </div>
                    <div class="footer-items">
                        <h2>Follow US</h2>
                        <p>lorem ipsu is simply a dummy text of th printing and typesetting industry</p>
                        <i class="fa-brands fa-facebook-f facebook-socials"></i><i class="fa-brands fa-twitter twitter-socials"></i>
                    </div>
                    <div class="footer-items">
                        <h2>Contact US</h2>
                        <p>lorem ipsu is simply a dummy text of th printing and typesetting industry</p>
                    </div>
                </div>
                <div class="footer-row-two">
                    <div class="footer-items">
                        <h2>Information</h2>
                       <span>About Us</span>
                       <span>Information</span>
                       <span>Privacy policy</span>
                       <span>Terms and Conditions</span>
                    </div>
                    <div class="footer-items">
                        <h2>Services</h2>
                        <span>About Us</span>
                       <span>Information</span>
                       <span>Privacy policy</span>
                       <span>Terms and Conditions</span>
                    </div>
                    <div class="footer-items">
                        <h2>My Account</h2>
                        <span>About Us</span>
                       <span>Information</span>
                       <span>Privacy policy</span>
                       <span>Terms and Conditions</span>
                    </div>
                    <div class="footer-items">
                        <h2>Our Offers</h2>
                        <span>About Us</span>
                        <span>Information</span>
                        <span>Privacy policy</span>
                        <span>Terms and Conditions</span>
                    </div>
                </div>
           </footer>
         </div>
</body>
</html>